#!/bin/bash

EMP_DIR="Employees"
BACKUP_DIR="Backup"

mkdir -p "$EMP_DIR"
mkdir -p "$BACKUP_DIR"

GREEN='\033[0;32m'
RED='\033[0;31m'
BLUE='\033[1;34m'
YELLOW='\033[1;33m'
NC='\033[0m'

pause() {
    read -p "Press Enter to continue..."
}

while true
do
clear

echo -e "${BLUE}"
echo "=================================================="
echo "        LINUX OFFICE MANAGEMENT SYSTEM"
echo "=================================================="
echo -e "${NC}"
echo "1.  Add Employee Record"
echo "2.  View Employee Records"
echo "3.  Create Linux User"
echo "4.  Set User Password"
echo "5.  Create Department (Group)"
echo "6.  Add User to Department"
echo "7.  Change File Permission"
echo "8.  Backup Employee Records"
echo "9.  Show Current Directory"
echo "10. List Linux Users"
echo "11. List Linux Groups"
echo "12. Exit"
echo

read -p "Enter your choice: " choice

case $choice in

1)
    read -p "Enter Employee File Name: " file
    vim "$EMP_DIR/$file.txt"
    ;;

2)
    echo
    ls "$EMP_DIR"
    echo
    read -p "Enter file name: " file
    if [ -f "$EMP_DIR/$file.txt" ]; then
        cat "$EMP_DIR/$file.txt"
    else
        echo -e "${RED}File not found.${NC}"
    fi
    pause
    ;;

3)
    read -p "Enter Username: " user
    sudo useradd "$user"
    pause
    ;;

4)
    read -p "Enter Username: " user
    sudo passwd "$user"
    pause
    ;;

5)
    read -p "Enter Group Name: " group
    sudo groupadd "$group"
    pause
    ;;

6)
    read -p "Enter Username: " user
    read -p "Enter Group Name: " group
    sudo usermod -aG "$group" "$user"
    pause
    ;;

7)
    ls "$EMP_DIR"
    read -p "Enter File Name: " file
    read -p "Enter Permission (Example: 755): " permission
    chmod "$permission" "$EMP_DIR/$file.txt"
    echo -e "${GREEN}Permission Updated Successfully.${NC}"
    pause
    ;;

8)
    cp -r "$EMP_DIR" "$BACKUP_DIR"
    echo -e "${GREEN}Backup Created Successfully.${NC}"
    pause
    ;;

9)
    pwd
    pause
    ;;

10)
    cut -d: -f1 /etc/passwd
    pause
    ;;

11)
    cut -d: -f1 /etc/group
    pause
    ;;

12)
    echo "Thank you for using Linux Office Management System."
    exit
    ;;

*)
    echo -e "${RED}Invalid Choice!${NC}"
    sleep 2
    ;;

esac

done
